Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"  # Image that can be found on Vagrant Cloud
  config.vm.hostname = "node01" # VM hostname
  config.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "k8network"
  # Customize memory and CPU:
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    vb.name = "node01" # Vm name
  end
end
